### ISSUE TITLE
strategy_tests failure

### ISSUE THREAD

**Issue by pjh40** [LLNL/Umpire#180] opened 2019-07-16 14:42 UTC
**Describe the bug*

During the execution of strategy_tests, I get the following failure on the fourth iteration of the loop at line 167 of strategy_tests.cpp:
[ERROR][/home/phenning/UmpProj/pkg/Umpire/src/umpire/alloc/CudaMallocAllocator.hpp:35]: allocate cudaMalloc( bytes = 4029677568 ) failed with error: out of memory
/home/phenning/UmpProj/pkg/Umpire/tests/integration/strategy_tests.cpp:172: Failure
Expected: { alloc1 = allocator.allocate(alloc_size); } doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] Strategy.Device (313179 ms)

The long execution time is due to some debugging code I added, which allowed me to monitor device memory usage with nvidia-smi.  What I saw at the top of each iteration on GPU 0 was:
829MiB / 16130MiB 
4669MiB / 16130MiB
8511MiB / 16130MiB
12353MiB / 16130MiB  (next allocation fails)
After adding a bit more debugging code, I note that the "allocator.deallocate(alloc1)" call never makes it to CudaMallocAllocator::deallocate(), although each allocator.alloc() call does call CudaMallocAllocator::allocate().

Any suggestions as to how I can track this down?

**Compilers & Libraries (please complete the following information):**
  1) cmake/3.12.4
  2) git/2.17.1
  3) cuda/10.1
  4) gcc/7.3.0
  5) ibm/xlc-16.1.1.2-xlf-16.1.1.2-gcc-7.3.0
 - CUDA version (if applicable): 

**Additional context**
Power9 system (Darwin at lanl)

Tue Jul 16 08:40:08 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000004:04:00.0 Off |                    0 |
| N/A   24C    P0    31W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000035:03:00.0 Off |                    0 |
| N/A   26C    P0    33W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------

**Comment by pjh40** [comment] 2019-07-16 14:50
Sorry, actually using the ibm/xlc-16.1.1.3-xlf-16.1.1.3 compilers.

**Comment by jdahm** [comment] 2019-07-16 16:42
Hi @pjh40, Thanks for reporting this! It looks like some (of my) recent pull request merges broke this test, and the CI tests didn't catch it. I'm working on a fix for this and an issue and logging, and should have things back to normal soon. For the time being, @davidbeckingsale reported to me that commit `7f1c921` works, in case you want to roll back to a working version newer than the last release.

**Comment by jdahm** [comment] 2019-07-16 18:16
The last fix is about to be merged to the `release/1.0.0` branch. It should be all ready in a few minutes.

**Comment by jdahm** [comment] 2019-07-16 18:41
Hi Paul, We've merged the fixes and tested them on LLNL systems. Could you give the code a try on your end and close the PR if the issue is resolved? Thanks!

**Comment by pjh40** [comment] 2019-07-16 19:26
Thanks for the patch.  All tests passed successfully with gcc/7.3.0, configured with:
    -DENABLE_MPI=OFF \
    -DENABLE_CUDA=On \
    -DENABLE_C=ON \
    -DENABLE_FORTRAN=OFF \
    -DCMAKE_BUILD_TYPE=Release \

**Closed** 2019-07-16 19:26 UTC
